version: '2'

services:
  postgres:
    image: 'armhf/postgres:9.6-alpine'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  redis:
    image: 'armhf/redis:3.2'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "scoring.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/scoring'
    ports:
      - '8000:8000'

  updates:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" --reload "scoring.app:create_background_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/scoring'
    ports:
      - '5000:8000'

  celery:
    build: .
    command: celery worker -B -l info -A scoring.blueprints.updates.tasks
    env_file:
      - '.env'
    volumes:
      - '.:/scoring'

volumes:
  postgres:
  redis:
